### ISSUE TITLE
`TODO` in source

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/PatternClass#13]
https://github.com/gap-packages/PatternClass/search?utf8=%E2%9C%93&q=TODO&type= 

returns several results - perhaps you can fill them in now, except `SupportEmail   := "TODO",` line from `PackageInfo.g` which is optional and may be deleted (you have issue tracker and that is the support channel).

**Comment by ruthhoffmann** [comment]
All TODO's have been removed or filled in.
