### ISSUE TITLE
Recording software outputs in Pure

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/PatternClass#19]
Please consider recording this software in Pure following the guidelines from https://code4ref.github.io/ (more specifically for Pure - https://code4ref.github.io/pure.html). This will allow us to have a better picture of all the variety of research software developed in St Andrews and get to know people behind it, and in its turn will help to campaign for the recognition of RSE roles at local and national (through https://rse.ac.uk/) levels.

**Comment by ruthhoffmann** [comment]
I believe it is already there and I think in the right format. If not, I will have a look into it. Thanks for the links!
https://risweb.st-andrews.ac.uk/portal/en/researchoutput/patternclass-version-242(1d635057-5630-468c-81ea-a4a1ef36ab1e).html

**Comment by olexandr-konovalov** [comment]
Ah, true! That's actually the latest release. Thanks!
