### ISSUE TITLE
README outdated?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/PatternClass#2]
The package README currently contains this:
> We had to patch the IntersectionAutomaton, UnionAutomata and ProductLanguage
> from the Automata pkg (version 1.13) to improve performance testing. The
> patched functions are located in lib/aux.* .
But no such files exist, and from a quick look, it seemed you now solved this problem by renaming your functions to `NDIntersectionAutomaton`, `NDUnionAutomata`, `NDProductOfLanguages`.

**Comment by ruthhoffmann** [comment]
That was a mistake in the README, the patches are located in lib/automata.* 
This has now been fixed.
