### ISSUE TITLE
Corrupted PackageInfo.g

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/PatternClass#6]
The file at https://ruthhoffmann.github.io/PatternClass/PackageInfo.g is corrupted (see the fragment below) - could you please replace it by exactly the PackageInfo.g file from version 2.4 archive? Thanks.

```
<<<<<<< HEAD
Version := "2.4",
Date := "11/08/2017", # dd/mm/yyyy format
=======
Version := "2.3",
Date := "05/07/2017", # dd/mm/yyyy format
>>>>>>> 408e1d7a14b0730ea44ccb107a34242449f26fa3

Persons := [
  rec(
    IsAuthor := true,
    IsMaintainer := true,
    FirstNames := "Ruth",
    LastName := "Hoffmann",
<<<<<<< HEAD
    WWWHome := "https://rh347.host.cs.st-andrews.ac.uk/",
=======
    WWWHome := "https://www.hoffmannandco.com",
>>>>>>> 408e1d7a14b0730ea44ccb107a34242449f26fa3
```

**Comment by ruthhoffmann** [comment]
Thanks! I had merge issues and must have missed this. Will fix this and issue #5 asap.

**Comment by olexandr-konovalov** [comment]
@ruthhoffmann thanks. Issue #5 requires new release, while fixing this does not - but important to replace  PackageInfo.g by exactly the PackageInfo.g file from version 2.4 archive.

**Comment by ruthhoffmann** [comment]
PackageInfo should be fixed now.
