### ISSUE TITLE
License declaration missing

### ISSUE THREAD

**Issue by jengelh** [gap-packages/PatternClass#7]
The package does not have a declaration of what license applies. This makes it impossible to distribute with Linux distributions.
Methods that were tried to find any declaration: locate a file whose name matches /copying/i, locate a file whose name matches /license/, locate a file /readme/ which mentions the word /license/i, locate any non-autogenerated file containing the words /gnu.general/i or /warranty/i.

**Comment by ChrisJefferson** [comment]
At some point when we are both at work, I can tell you about the licence options you can choose from, and their positive and negative points :)

**Comment by ChrisJefferson** [comment]
@jengelh : Your message is very unhelpful, and quite confusing. If you are going to use it in future, I would recommend simplifying it and removing pointless "techno-speak".

Most people (including me) have no idea what /copying/i means, or why we would care about finding gnu.general.

**Comment by jengelh** [comment]
It is sometimes used to denote a regular expression. Translated, this means: there is no file by the name of "COPYING", "copying" (or any other spelling variant), and that there is no file which contains the words "GNU General", indicative of GNU GPL licensing, nor a file containing the word "WARRANTY", which would be indicative of some BSD-like licensing terms.

**Comment by olexandr-konovalov** [comment]
@ruthhoffmann I might try to release new version later today - would you be able to address this, please?

**Comment by ruthhoffmann** [comment]
Thanks to @ChrisJefferson this has now been added.
